/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c ServerInfo -a ./server/serverinfo.h:./server/serverinfo.cpp test.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./server/serverinfo.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ServerInfo
 */

ServerInfo::ServerInfo(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ServerInfo::~ServerInfo()
{
    // destructor
}

int ServerInfo::add(int va, int vb, QString &sum_str)
{
    // handle method call org.wx.test.interface1.add
    //return static_cast<YourObjectType *>(parent())->add(va, vb, sum_str);
}

void ServerInfo::print(const QString &value)
{
    // handle method call org.wx.test.interface1.print
    QMetaObject::invokeMethod(parent(), "print", Q_ARG(QString, value));
}

/*
 * Implementation of adaptor class ServerInfo
 */

ServerInfo2::ServerInfo2(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ServerInfo2::~ServerInfo2()
{
    // destructor
}

QDBusVariant ServerInfo2::transfer(const QDBusVariant &in_data)
{
    // handle method call org.wx.test.interface2.transfer
    QDBusVariant out_data;
    QMetaObject::invokeMethod(parent(), "transfer", Q_RETURN_ARG(QDBusVariant, out_data), Q_ARG(QDBusVariant, in_data));
    return out_data;
}

