/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c ServerInfo -a serverinfo.h:serverinfo.cpp test.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SERVERINFO_H
#define SERVERINFO_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.wx.test.interface1
 */
class ServerInfo: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.wx.test.interface1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.wx.test.interface1\">\n"
"    <method name=\"print\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"add\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"va\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"vb\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"sum\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"sum_str\"/>\n"
"    </method>\n"
"    <signal name=\"boradcast\">\n"
"      <arg type=\"s\" name=\"data\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    ServerInfo(QObject *parent);
    virtual ~ServerInfo();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int add(int va, int vb, QString &sum_str);
    void print(const QString &value);
Q_SIGNALS: // SIGNALS
    void boradcast(const QString &data);
};

/*
 * Adaptor class for interface org.wx.test.interface2
 */
class ServerInfo2: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.wx.test.interface2")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.wx.test.interface2\">\n"
"    <method name=\"transfer\">\n"
"      <arg direction=\"in\" type=\"v\" name=\"in_data\"/>\n"
"      <arg direction=\"out\" type=\"v\" name=\"out_data\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ServerInfo2(QObject *parent);
    virtual ~ServerInfo2();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusVariant transfer(const QDBusVariant &in_data);
Q_SIGNALS: // SIGNALS
};

#endif
