/*
 * Generated by gdbus-codegen 2.40.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "test.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.wx.test.interface1
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:Interface1
 * @title: Interface1
 * @short_description: Generated C code for the org.wx.test.interface1 D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-wx-test-interface1.top_of_page">org.wx.test.interface1</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.wx.test.interface1 ---- */

static const _ExtendedGDBusArgInfo _interface1_method_info_print_IN_ARG_value =
{
  {
    -1,
    (gchar *) "value",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _interface1_method_info_print_IN_ARG_pointers[] =
{
  &_interface1_method_info_print_IN_ARG_value,
  NULL
};

static const _ExtendedGDBusMethodInfo _interface1_method_info_print =
{
  {
    -1,
    (gchar *) "print",
    (GDBusArgInfo **) &_interface1_method_info_print_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-print",
  FALSE
};

static const _ExtendedGDBusArgInfo _interface1_method_info_add_IN_ARG_val =
{
  {
    -1,
    (gchar *) "val",
    (gchar *) "ai",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _interface1_method_info_add_IN_ARG_pointers[] =
{
  &_interface1_method_info_add_IN_ARG_val,
  NULL
};

static const _ExtendedGDBusArgInfo _interface1_method_info_add_OUT_ARG_sum =
{
  {
    -1,
    (gchar *) "sum",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _interface1_method_info_add_OUT_ARG_pointers[] =
{
  &_interface1_method_info_add_OUT_ARG_sum,
  NULL
};

static const _ExtendedGDBusMethodInfo _interface1_method_info_add =
{
  {
    -1,
    (gchar *) "add",
    (GDBusArgInfo **) &_interface1_method_info_add_IN_ARG_pointers,
    (GDBusArgInfo **) &_interface1_method_info_add_OUT_ARG_pointers,
    NULL
  },
  "handle-add",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _interface1_method_info_pointers[] =
{
  &_interface1_method_info_print,
  &_interface1_method_info_add,
  NULL
};

static const _ExtendedGDBusArgInfo _interface1_signal_info_boradcast_ARG_data =
{
  {
    -1,
    (gchar *) "data",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _interface1_signal_info_boradcast_ARG_pointers[] =
{
  &_interface1_signal_info_boradcast_ARG_data,
  NULL
};

static const _ExtendedGDBusSignalInfo _interface1_signal_info_boradcast =
{
  {
    -1,
    (gchar *) "boradcast",
    (GDBusArgInfo **) &_interface1_signal_info_boradcast_ARG_pointers,
    NULL
  },
  "boradcast"
};

static const _ExtendedGDBusSignalInfo * const _interface1_signal_info_pointers[] =
{
  &_interface1_signal_info_boradcast,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _interface1_interface_info =
{
  {
    -1,
    (gchar *) "org.wx.test.interface1",
    (GDBusMethodInfo **) &_interface1_method_info_pointers,
    (GDBusSignalInfo **) &_interface1_signal_info_pointers,
    NULL,
    NULL
  },
  "interface1",
};


/**
 * interface1_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-wx-test-interface1.top_of_page">org.wx.test.interface1</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
interface1_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_interface1_interface_info.parent_struct;
}

/**
 * interface1_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #Interface1 interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
interface1_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * Interface1:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-wx-test-interface1.top_of_page">org.wx.test.interface1</link>.
 */

/**
 * Interface1Iface:
 * @parent_iface: The parent interface.
 * @handle_add: Handler for the #Interface1::handle-add signal.
 * @handle_print: Handler for the #Interface1::handle-print signal.
 * @boradcast: Handler for the #Interface1::boradcast signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-wx-test-interface1.top_of_page">org.wx.test.interface1</link>.
 */

typedef Interface1Iface Interface1Interface;
G_DEFINE_INTERFACE (Interface1, interface1, G_TYPE_OBJECT);

static void
interface1_default_init (Interface1Iface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * Interface1::handle-print:
   * @object: A #Interface1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_value: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-wx-test-interface1.print">print()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call interface1_complete_print() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-print",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (Interface1Iface, handle_print),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * Interface1::handle-add:
   * @object: A #Interface1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_val: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-wx-test-interface1.add">add()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call interface1_complete_add() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-add",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (Interface1Iface, handle_add),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_VARIANT);

  /* GObject signals for received D-Bus signals: */
  /**
   * Interface1::boradcast:
   * @object: A #Interface1.
   * @arg_data: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-wx-test-interface1.boradcast">"boradcast"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("boradcast",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (Interface1Iface, boradcast),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

}

/**
 * interface1_emit_boradcast:
 * @object: A #Interface1.
 * @arg_data: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-wx-test-interface1.boradcast">"boradcast"</link> D-Bus signal.
 */
void
interface1_emit_boradcast (
    Interface1 *object,
    const gchar *arg_data)
{
  g_signal_emit_by_name (object, "boradcast", arg_data);
}

/**
 * interface1_call_print:
 * @proxy: A #Interface1Proxy.
 * @arg_value: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-wx-test-interface1.print">print()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call interface1_call_print_finish() to get the result of the operation.
 *
 * See interface1_call_print_sync() for the synchronous, blocking version of this method.
 */
void
interface1_call_print (
    Interface1 *proxy,
    const gchar *arg_value,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "print",
    g_variant_new ("(s)",
                   arg_value),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * interface1_call_print_finish:
 * @proxy: A #Interface1Proxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to interface1_call_print().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with interface1_call_print().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
interface1_call_print_finish (
    Interface1 *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * interface1_call_print_sync:
 * @proxy: A #Interface1Proxy.
 * @arg_value: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-wx-test-interface1.print">print()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See interface1_call_print() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
interface1_call_print_sync (
    Interface1 *proxy,
    const gchar *arg_value,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "print",
    g_variant_new ("(s)",
                   arg_value),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * interface1_call_add:
 * @proxy: A #Interface1Proxy.
 * @arg_val: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-wx-test-interface1.add">add()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call interface1_call_add_finish() to get the result of the operation.
 *
 * See interface1_call_add_sync() for the synchronous, blocking version of this method.
 */
void
interface1_call_add (
    Interface1 *proxy,
    GVariant *arg_val,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "add",
    g_variant_new ("(@ai)",
                   arg_val),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * interface1_call_add_finish:
 * @proxy: A #Interface1Proxy.
 * @out_sum: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to interface1_call_add().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with interface1_call_add().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
interface1_call_add_finish (
    Interface1 *proxy,
    gint *out_sum,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_sum);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * interface1_call_add_sync:
 * @proxy: A #Interface1Proxy.
 * @arg_val: Argument to pass with the method invocation.
 * @out_sum: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-wx-test-interface1.add">add()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See interface1_call_add() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
interface1_call_add_sync (
    Interface1 *proxy,
    GVariant *arg_val,
    gint *out_sum,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "add",
    g_variant_new ("(@ai)",
                   arg_val),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_sum);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * interface1_complete_print:
 * @object: A #Interface1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-wx-test-interface1.print">print()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
interface1_complete_print (
    Interface1 *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * interface1_complete_add:
 * @object: A #Interface1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @sum: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-wx-test-interface1.add">add()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
interface1_complete_add (
    Interface1 *object,
    GDBusMethodInvocation *invocation,
    gint sum)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(i)",
                   sum));
}

/* ------------------------------------------------------------------------ */

/**
 * Interface1Proxy:
 *
 * The #Interface1Proxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * Interface1ProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #Interface1Proxy.
 */

struct _Interface1ProxyPrivate
{
  GData *qdata;
};

static void interface1_proxy_iface_init (Interface1Iface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (Interface1Proxy, interface1_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (Interface1Proxy)
                         G_IMPLEMENT_INTERFACE (TYPE_INTERFACE1, interface1_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (Interface1Proxy, interface1_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_INTERFACE1, interface1_proxy_iface_init));

#endif
static void
interface1_proxy_finalize (GObject *object)
{
  Interface1Proxy *proxy = INTERFACE1_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (interface1_proxy_parent_class)->finalize (object);
}

static void
interface1_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
interface1_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
interface1_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_interface1_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_INTERFACE1);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_INTERFACE1);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
interface1_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  Interface1Proxy *proxy = INTERFACE1_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_interface1_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_interface1_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
interface1_proxy_init (Interface1Proxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = interface1_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_INTERFACE1_PROXY, Interface1ProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), interface1_interface_info ());
}

static void
interface1_proxy_class_init (Interface1ProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = interface1_proxy_finalize;
  gobject_class->get_property = interface1_proxy_get_property;
  gobject_class->set_property = interface1_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = interface1_proxy_g_signal;
  proxy_class->g_properties_changed = interface1_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (Interface1ProxyPrivate));
#endif
}

static void
interface1_proxy_iface_init (Interface1Iface *iface)
{
}

/**
 * interface1_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-wx-test-interface1.top_of_page">org.wx.test.interface1</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call interface1_proxy_new_finish() to get the result of the operation.
 *
 * See interface1_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
interface1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_INTERFACE1_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.wx.test.interface1", NULL);
}

/**
 * interface1_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to interface1_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with interface1_proxy_new().
 *
 * Returns: (transfer full) (type Interface1Proxy): The constructed proxy object or %NULL if @error is set.
 */
Interface1 *
interface1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return INTERFACE1 (ret);
  else
    return NULL;
}

/**
 * interface1_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-wx-test-interface1.top_of_page">org.wx.test.interface1</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See interface1_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type Interface1Proxy): The constructed proxy object or %NULL if @error is set.
 */
Interface1 *
interface1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_INTERFACE1_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.wx.test.interface1", NULL);
  if (ret != NULL)
    return INTERFACE1 (ret);
  else
    return NULL;
}


/**
 * interface1_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like interface1_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call interface1_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See interface1_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
interface1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_INTERFACE1_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.wx.test.interface1", NULL);
}

/**
 * interface1_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to interface1_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with interface1_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type Interface1Proxy): The constructed proxy object or %NULL if @error is set.
 */
Interface1 *
interface1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return INTERFACE1 (ret);
  else
    return NULL;
}

/**
 * interface1_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like interface1_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See interface1_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type Interface1Proxy): The constructed proxy object or %NULL if @error is set.
 */
Interface1 *
interface1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_INTERFACE1_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.wx.test.interface1", NULL);
  if (ret != NULL)
    return INTERFACE1 (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * Interface1Skeleton:
 *
 * The #Interface1Skeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * Interface1SkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #Interface1Skeleton.
 */

struct _Interface1SkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_interface1_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  Interface1Skeleton *skeleton = INTERFACE1_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_INTERFACE1);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_INTERFACE1);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_interface1_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  Interface1Skeleton *skeleton = INTERFACE1_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_interface1_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_interface1_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  Interface1Skeleton *skeleton = INTERFACE1_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_interface1_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _interface1_skeleton_vtable =
{
  _interface1_skeleton_handle_method_call,
  _interface1_skeleton_handle_get_property,
  _interface1_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
interface1_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return interface1_interface_info ();
}

static GDBusInterfaceVTable *
interface1_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_interface1_skeleton_vtable;
}

static GVariant *
interface1_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  Interface1Skeleton *skeleton = INTERFACE1_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_interface1_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _interface1_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _interface1_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _interface1_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.wx.test.interface1", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
interface1_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_interface1_on_signal_boradcast (
    Interface1 *object,
    const gchar *arg_data)
{
  Interface1Skeleton *skeleton = INTERFACE1_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(s)",
                   arg_data));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.wx.test.interface1", "boradcast",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void interface1_skeleton_iface_init (Interface1Iface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (Interface1Skeleton, interface1_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (Interface1Skeleton)
                         G_IMPLEMENT_INTERFACE (TYPE_INTERFACE1, interface1_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (Interface1Skeleton, interface1_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_INTERFACE1, interface1_skeleton_iface_init));

#endif
static void
interface1_skeleton_finalize (GObject *object)
{
  Interface1Skeleton *skeleton = INTERFACE1_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (interface1_skeleton_parent_class)->finalize (object);
}

static void
interface1_skeleton_init (Interface1Skeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = interface1_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_INTERFACE1_SKELETON, Interface1SkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
interface1_skeleton_class_init (Interface1SkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = interface1_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = interface1_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = interface1_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = interface1_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = interface1_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (Interface1SkeletonPrivate));
#endif
}

static void
interface1_skeleton_iface_init (Interface1Iface *iface)
{
  iface->boradcast = _interface1_on_signal_boradcast;
}

/**
 * interface1_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-wx-test-interface1.top_of_page">org.wx.test.interface1</link>.
 *
 * Returns: (transfer full) (type Interface1Skeleton): The skeleton object.
 */
Interface1 *
interface1_skeleton_new (void)
{
  return INTERFACE1 (g_object_new (TYPE_INTERFACE1_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for interface org.wx.test.interface2
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:Interface2
 * @title: Interface2
 * @short_description: Generated C code for the org.wx.test.interface2 D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-wx-test-interface2.top_of_page">org.wx.test.interface2</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.wx.test.interface2 ---- */

static const _ExtendedGDBusArgInfo _interface2_method_info_transfer_IN_ARG_in_data =
{
  {
    -1,
    (gchar *) "in_data",
    (gchar *) "v",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _interface2_method_info_transfer_IN_ARG_pointers[] =
{
  &_interface2_method_info_transfer_IN_ARG_in_data,
  NULL
};

static const _ExtendedGDBusArgInfo _interface2_method_info_transfer_OUT_ARG_out_data =
{
  {
    -1,
    (gchar *) "out_data",
    (gchar *) "v",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _interface2_method_info_transfer_OUT_ARG_pointers[] =
{
  &_interface2_method_info_transfer_OUT_ARG_out_data,
  NULL
};

static const _ExtendedGDBusMethodInfo _interface2_method_info_transfer =
{
  {
    -1,
    (gchar *) "transfer",
    (GDBusArgInfo **) &_interface2_method_info_transfer_IN_ARG_pointers,
    (GDBusArgInfo **) &_interface2_method_info_transfer_OUT_ARG_pointers,
    NULL
  },
  "handle-transfer",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _interface2_method_info_pointers[] =
{
  &_interface2_method_info_transfer,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _interface2_interface_info =
{
  {
    -1,
    (gchar *) "org.wx.test.interface2",
    (GDBusMethodInfo **) &_interface2_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "interface2",
};


/**
 * interface2_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-wx-test-interface2.top_of_page">org.wx.test.interface2</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
interface2_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_interface2_interface_info.parent_struct;
}

/**
 * interface2_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #Interface2 interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
interface2_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * Interface2:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-wx-test-interface2.top_of_page">org.wx.test.interface2</link>.
 */

/**
 * Interface2Iface:
 * @parent_iface: The parent interface.
 * @handle_transfer: Handler for the #Interface2::handle-transfer signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-wx-test-interface2.top_of_page">org.wx.test.interface2</link>.
 */

typedef Interface2Iface Interface2Interface;
G_DEFINE_INTERFACE (Interface2, interface2, G_TYPE_OBJECT);

static void
interface2_default_init (Interface2Iface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * Interface2::handle-transfer:
   * @object: A #Interface2.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_in_data: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-wx-test-interface2.transfer">transfer()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call interface2_complete_transfer() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-transfer",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (Interface2Iface, handle_transfer),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_VARIANT);

}

/**
 * interface2_call_transfer:
 * @proxy: A #Interface2Proxy.
 * @arg_in_data: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-wx-test-interface2.transfer">transfer()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call interface2_call_transfer_finish() to get the result of the operation.
 *
 * See interface2_call_transfer_sync() for the synchronous, blocking version of this method.
 */
void
interface2_call_transfer (
    Interface2 *proxy,
    GVariant *arg_in_data,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "transfer",
    g_variant_new ("(@v)",
                   arg_in_data),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * interface2_call_transfer_finish:
 * @proxy: A #Interface2Proxy.
 * @out_out_data: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to interface2_call_transfer().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with interface2_call_transfer().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
interface2_call_transfer_finish (
    Interface2 *proxy,
    GVariant **out_out_data,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@v)",
                 out_out_data);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * interface2_call_transfer_sync:
 * @proxy: A #Interface2Proxy.
 * @arg_in_data: Argument to pass with the method invocation.
 * @out_out_data: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-wx-test-interface2.transfer">transfer()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See interface2_call_transfer() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
interface2_call_transfer_sync (
    Interface2 *proxy,
    GVariant *arg_in_data,
    GVariant **out_out_data,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "transfer",
    g_variant_new ("(@v)",
                   arg_in_data),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@v)",
                 out_out_data);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * interface2_complete_transfer:
 * @object: A #Interface2.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @out_data: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-wx-test-interface2.transfer">transfer()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
interface2_complete_transfer (
    Interface2 *object,
    GDBusMethodInvocation *invocation,
    GVariant *out_data)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@v)",
                   out_data));
}

/* ------------------------------------------------------------------------ */

/**
 * Interface2Proxy:
 *
 * The #Interface2Proxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * Interface2ProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #Interface2Proxy.
 */

struct _Interface2ProxyPrivate
{
  GData *qdata;
};

static void interface2_proxy_iface_init (Interface2Iface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (Interface2Proxy, interface2_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (Interface2Proxy)
                         G_IMPLEMENT_INTERFACE (TYPE_INTERFACE2, interface2_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (Interface2Proxy, interface2_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_INTERFACE2, interface2_proxy_iface_init));

#endif
static void
interface2_proxy_finalize (GObject *object)
{
  Interface2Proxy *proxy = INTERFACE2_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (interface2_proxy_parent_class)->finalize (object);
}

static void
interface2_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
interface2_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
interface2_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_interface2_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_INTERFACE2);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_INTERFACE2);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
interface2_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  Interface2Proxy *proxy = INTERFACE2_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_interface2_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_interface2_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
interface2_proxy_init (Interface2Proxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = interface2_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_INTERFACE2_PROXY, Interface2ProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), interface2_interface_info ());
}

static void
interface2_proxy_class_init (Interface2ProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = interface2_proxy_finalize;
  gobject_class->get_property = interface2_proxy_get_property;
  gobject_class->set_property = interface2_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = interface2_proxy_g_signal;
  proxy_class->g_properties_changed = interface2_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (Interface2ProxyPrivate));
#endif
}

static void
interface2_proxy_iface_init (Interface2Iface *iface)
{
}

/**
 * interface2_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-wx-test-interface2.top_of_page">org.wx.test.interface2</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call interface2_proxy_new_finish() to get the result of the operation.
 *
 * See interface2_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
interface2_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_INTERFACE2_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.wx.test.interface2", NULL);
}

/**
 * interface2_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to interface2_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with interface2_proxy_new().
 *
 * Returns: (transfer full) (type Interface2Proxy): The constructed proxy object or %NULL if @error is set.
 */
Interface2 *
interface2_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return INTERFACE2 (ret);
  else
    return NULL;
}

/**
 * interface2_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-wx-test-interface2.top_of_page">org.wx.test.interface2</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See interface2_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type Interface2Proxy): The constructed proxy object or %NULL if @error is set.
 */
Interface2 *
interface2_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_INTERFACE2_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.wx.test.interface2", NULL);
  if (ret != NULL)
    return INTERFACE2 (ret);
  else
    return NULL;
}


/**
 * interface2_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like interface2_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call interface2_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See interface2_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
interface2_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_INTERFACE2_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.wx.test.interface2", NULL);
}

/**
 * interface2_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to interface2_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with interface2_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type Interface2Proxy): The constructed proxy object or %NULL if @error is set.
 */
Interface2 *
interface2_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return INTERFACE2 (ret);
  else
    return NULL;
}

/**
 * interface2_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like interface2_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See interface2_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type Interface2Proxy): The constructed proxy object or %NULL if @error is set.
 */
Interface2 *
interface2_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_INTERFACE2_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.wx.test.interface2", NULL);
  if (ret != NULL)
    return INTERFACE2 (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * Interface2Skeleton:
 *
 * The #Interface2Skeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * Interface2SkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #Interface2Skeleton.
 */

struct _Interface2SkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_interface2_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  Interface2Skeleton *skeleton = INTERFACE2_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_INTERFACE2);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_INTERFACE2);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_interface2_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  Interface2Skeleton *skeleton = INTERFACE2_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_interface2_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_interface2_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  Interface2Skeleton *skeleton = INTERFACE2_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_interface2_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _interface2_skeleton_vtable =
{
  _interface2_skeleton_handle_method_call,
  _interface2_skeleton_handle_get_property,
  _interface2_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
interface2_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return interface2_interface_info ();
}

static GDBusInterfaceVTable *
interface2_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_interface2_skeleton_vtable;
}

static GVariant *
interface2_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  Interface2Skeleton *skeleton = INTERFACE2_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_interface2_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _interface2_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _interface2_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _interface2_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.wx.test.interface2", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
interface2_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void interface2_skeleton_iface_init (Interface2Iface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (Interface2Skeleton, interface2_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (Interface2Skeleton)
                         G_IMPLEMENT_INTERFACE (TYPE_INTERFACE2, interface2_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (Interface2Skeleton, interface2_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_INTERFACE2, interface2_skeleton_iface_init));

#endif
static void
interface2_skeleton_finalize (GObject *object)
{
  Interface2Skeleton *skeleton = INTERFACE2_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (interface2_skeleton_parent_class)->finalize (object);
}

static void
interface2_skeleton_init (Interface2Skeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = interface2_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_INTERFACE2_SKELETON, Interface2SkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
interface2_skeleton_class_init (Interface2SkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = interface2_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = interface2_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = interface2_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = interface2_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = interface2_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (Interface2SkeletonPrivate));
#endif
}

static void
interface2_skeleton_iface_init (Interface2Iface *iface)
{
}

/**
 * interface2_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-wx-test-interface2.top_of_page">org.wx.test.interface2</link>.
 *
 * Returns: (transfer full) (type Interface2Skeleton): The skeleton object.
 */
Interface2 *
interface2_skeleton_new (void)
{
  return INTERFACE2 (g_object_new (TYPE_INTERFACE2_SKELETON, NULL));
}

